[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "interop-lib/=lib/interop-lib/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
